import React, { useState } from 'react';
import { Landmark, Copy, Check, Printer } from 'lucide-react';
import type { ResearchBrief } from '../../types';
import { Button } from '../common/Button';

interface ResearchBriefViewProps {
  brief: ResearchBrief;
}

export const ResearchBriefView: React.FC<ResearchBriefViewProps> = ({ brief }) => {
  const [isCopied, setIsCopied] = useState<boolean>(false);

  const evidenceList = brief.evidence || brief.evidenceRegister || [];
  const keyFindingsList = brief.keyFindings || [];
  const implicationsList = Array.isArray(brief.implications)
    ? brief.implications
    : brief.implications
    ? [brief.implications]
    : [];
  const limitationsList = Array.isArray(brief.limitations)
    ? brief.limitations
    : brief.limitations
    ? [brief.limitations]
    : [];
  const sourcesList = brief.sources || [];

  const handlePrint = () => {
    window.print();
  };

  const handleCopyToClipboard = async () => {
    const sections: string[] = [];

    sections.push(`GOVERNMENT LEGISLATIVE POLICY BRIEF: ${brief.title.toUpperCase()}`);
    sections.push('========================================================');
    if (brief.subject) sections.push(`SUBJECT: ${brief.subject}`);
    if (brief.topic) sections.push(`TOPIC: ${brief.topic}`);
    if (brief.ministry) sections.push(`ISSUING MINISTRY: ${brief.ministry}`);
    if (brief.gazetteDate) sections.push(`GAZETTE DATE: ${brief.gazetteDate}`);
    if (brief.authorDivision) sections.push(`PREPARED BY: ${brief.authorDivision}`);
    if (brief.generatedAt) sections.push(`DATE: ${new Date(brief.generatedAt).toLocaleDateString()}`);
    sections.push('--------------------------------------------------------\n');

    if (brief.executiveSummary) {
      sections.push(`1. EXECUTIVE SUMMARY\n${brief.executiveSummary}\n`);
    }

    if (brief.background) {
      sections.push(`2. BACKGROUND\n${brief.background}\n`);
    }

    if (keyFindingsList.length > 0) {
      sections.push(
        `3. KEY FINDINGS\n` +
          keyFindingsList
            .map((f, i) =>
              typeof f === 'string'
                ? `[${i + 1}] ${f}`
                : `[${i + 1}] ${f.title || 'Finding'}: ${f.summary || ''} (${f.mandateLevel || 'Mandatory'}${f.enforcingAgency ? ` | Agency: ${f.enforcingAgency}` : ''})`
            )
            .join('\n') +
          '\n'
      );
    }

    if (brief.policyAnalysis) {
      sections.push(`4. POLICY ANALYSIS\n${brief.policyAnalysis}\n`);
    }

    if (evidenceList.length > 0) {
      sections.push(
        `5. GROUNDED EVIDENCE\n` +
          evidenceList
            .map(
              (e, i) =>
                `[${i + 1}] “${e.excerptQuote}” — ${e.documentTitle || 'Source'} (Page ${e.pageNumber ?? 'N/A'}${e.sectionHeading ? `, ${e.sectionHeading}` : ''})`
            )
            .join('\n') +
          '\n'
      );
    }

    if (implicationsList.length > 0) {
      sections.push(`6. POLICY IMPLICATIONS\n` + implicationsList.map((imp) => `• ${imp}`).join('\n') + '\n');
    }

    if (limitationsList.length > 0) {
      sections.push(`7. LIMITATIONS & UNCERTAINTIES\n` + limitationsList.map((lim) => `• ${lim}`).join('\n') + '\n');
    }

    if (sourcesList.length > 0) {
      sections.push(
        `8. OFFICIAL SOURCES\n` +
          sourcesList
            .map((s, i) => `[${i + 1}] ${s.title || s.documentId || 'Document'}${s.pageNumber ? ` (Page ${s.pageNumber})` : ''}`)
            .join('\n') +
          '\n'
      );
    }

    sections.push('--------------------------------------------------------');
    sections.push('Generated by PolicyIntelligence Platform • WCAG 2.2 AA');

    try {
      await navigator.clipboard.writeText(sections.join('\n'));
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2500);
    } catch {
      // Fallback
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      {/* Top Action Bar (Hidden in Print) */}
      <div
        className="no-print"
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          flexWrap: 'wrap',
          gap: '1rem',
          paddingBottom: '1rem',
          borderBottom: '1px solid var(--gov-slate-200)',
        }}
      >
        <div style={{ fontSize: '0.875rem', color: 'var(--gov-slate-600)' }}>
          Official Parliamentary Research Brief dossier.
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
          <Button
            type="button"
            variant="secondary"
            onClick={handleCopyToClipboard}
            icon={isCopied ? <Check size={16} aria-hidden="true" /> : <Copy size={16} aria-hidden="true" />}
          >
            {isCopied ? 'Copied to Clipboard' : 'Copy Text'}
          </Button>

          <Button
            type="button"
            variant="primary"
            onClick={handlePrint}
            icon={<Printer size={16} aria-hidden="true" />}
          >
            Print Dossier / Save PDF
          </Button>
        </div>
      </div>

      {/* Official Government Research Brief Paper Sheet */}
      <article
        className="policy-dossier-sheet"
        style={{
          background: 'var(--gov-white)',
          border: '1px solid var(--gov-slate-300)',
          borderRadius: 'var(--radius-md)',
          padding: '2.5rem',
          boxShadow: 'var(--shadow-md)',
          maxWidth: '920px',
          width: '100%',
          margin: '0 auto',
          color: '#111827',
        }}
        data-testid="research-brief-content"
      >
        {/* Memorandum Header */}
        <header
          style={{
            borderBottom: '2px solid var(--gov-navy-950)',
            paddingBottom: '1.5rem',
            marginBottom: '2rem',
          }}
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1.25rem' }}>
            <Landmark size={32} style={{ color: 'var(--gov-navy-950)' }} aria-hidden="true" />
            <div>
              <h2
                style={{
                  fontSize: '1.375rem',
                  fontWeight: 800,
                  textTransform: 'uppercase',
                  letterSpacing: '0.04em',
                  margin: 0,
                  color: 'var(--gov-navy-950)',
                }}
              >
                {brief.title}
              </h2>
              <div style={{ fontSize: '0.8125rem', color: 'var(--gov-slate-600)', marginTop: '0.2rem' }}>
                {brief.authorDivision || 'Statutory Research & Policy Assessment Division'}
              </div>
            </div>
          </div>

          <div
            style={{
              display: 'grid',
              gridTemplateColumns: 'auto 1fr',
              columnGap: '1rem',
              rowGap: '0.4rem',
              fontSize: '0.875rem',
              fontFamily: 'var(--font-mono, monospace)',
            }}
          >
            {brief.subject && (
              <>
                <strong>SUBJECT:</strong>
                <span>{brief.subject}</span>
              </>
            )}
            {brief.topic && (
              <>
                <strong>TOPIC:</strong>
                <span>{brief.topic}</span>
              </>
            )}
            {brief.ministry && (
              <>
                <strong>MINISTRY:</strong>
                <span>{brief.ministry}</span>
              </>
            )}
            {brief.gazetteDate && (
              <>
                <strong>GAZETTE DATE:</strong>
                <span>{brief.gazetteDate}</span>
              </>
            )}
            {brief.generatedAt && (
              <>
                <strong>DATE GENERATED:</strong>
                <span>{new Date(brief.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>
              </>
            )}
          </div>
        </header>

        {/* Section 1: Executive Summary (Render ONLY if supplied) */}
        {brief.executiveSummary && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-executive-summary">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              1. Executive Summary
            </h3>
            <p style={{ lineHeight: '1.7', fontSize: '0.9375rem', color: 'var(--gov-slate-900)', margin: 0 }}>
              {brief.executiveSummary}
            </p>
          </section>
        )}

        {/* Section 2: Background (Render ONLY if supplied) */}
        {brief.background && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-background">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              2. Background & Legislative Context
            </h3>
            <p style={{ lineHeight: '1.7', fontSize: '0.9375rem', color: 'var(--gov-slate-900)', margin: 0 }}>
              {brief.background}
            </p>
          </section>
        )}

        {/* Section 3: Key Findings (Render ONLY if supplied) */}
        {keyFindingsList.length > 0 && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-key-findings">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              3. Key Statutory Findings
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
              {keyFindingsList.map((finding, idx) => {
                const key = finding.id || `kf-${idx}`;
                return (
                  <div key={key} style={{ padding: '0.75rem', backgroundColor: 'var(--gov-slate-50)', borderRadius: 'var(--radius-sm)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.25rem', flexWrap: 'wrap' }}>
                      <strong style={{ fontSize: '0.9375rem', color: 'var(--gov-navy-950)' }}>
                        3.{idx + 1} {finding.title || 'Statutory Finding'}
                      </strong>
                      {finding.mandateLevel && (
                        <span style={{ fontSize: '0.6875rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--gov-slate-600)' }}>
                          [{finding.mandateLevel}]
                        </span>
                      )}
                      {finding.enforcingAgency && (
                        <span style={{ fontSize: '0.75rem', color: 'var(--gov-navy-800)' }}>
                          • Agency: {finding.enforcingAgency}
                        </span>
                      )}
                    </div>
                    {finding.summary && (
                      <p style={{ fontSize: '0.875rem', lineHeight: 1.5, margin: '0.25rem 0 0 0', color: 'var(--gov-slate-800)' }}>
                        {finding.summary}
                      </p>
                    )}
                  </div>
                );
              })}
            </div>
          </section>
        )}

        {/* Section 4: Policy Analysis (Render ONLY if supplied) */}
        {brief.policyAnalysis && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-policy-analysis">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              4. Policy Analysis
            </h3>
            <p style={{ lineHeight: '1.7', fontSize: '0.9375rem', color: 'var(--gov-slate-900)', margin: 0 }}>
              {brief.policyAnalysis}
            </p>
          </section>
        )}

        {/* Section 5: Evidence (Render ONLY if supplied) */}
        {evidenceList.length > 0 && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-evidence">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              5. Grounded Statutory Evidence
            </h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
              {evidenceList.map((ev, idx) => (
                <div
                  key={ev.id || `ev-${idx}`}
                  style={{
                    padding: '0.75rem 1rem',
                    borderLeft: '3px solid var(--gov-navy-900)',
                    backgroundColor: 'var(--gov-slate-50)',
                    fontSize: '0.875rem',
                  }}
                >
                  <blockquote style={{ margin: '0 0 0.35rem 0', fontStyle: 'italic', color: 'var(--gov-slate-800)' }}>
                    “{ev.excerptQuote}”
                  </blockquote>
                  <div style={{ fontSize: '0.75rem', color: 'var(--gov-slate-600)' }}>
                    {ev.documentTitle && <strong>{ev.documentTitle}</strong>}
                    {ev.pageNumber != null && <span> (Page {ev.pageNumber})</span>}
                    {ev.sectionHeading && <span> • {ev.sectionHeading}</span>}
                  </div>
                </div>
              ))}
            </div>
          </section>
        )}

        {/* Section 6: Implications (Render ONLY if supplied) */}
        {implicationsList.length > 0 && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-implications">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              6. Policy Implications
            </h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.875rem', lineHeight: 1.6, color: 'var(--gov-slate-800)' }}>
              {implicationsList.map((imp, idx) => (
                <li key={`imp-${idx}-${imp.slice(0, 15)}`} style={{ marginBottom: '0.5rem' }}>
                  {imp}
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Section 7: Limitations (Render ONLY if supplied) */}
        {limitationsList.length > 0 && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-limitations">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              7. Analytical Limitations & Uncertainties
            </h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.875rem', lineHeight: 1.6, color: 'var(--gov-slate-800)' }}>
              {limitationsList.map((lim, idx) => (
                <li key={`lim-${idx}-${lim.slice(0, 15)}`} style={{ marginBottom: '0.5rem' }}>
                  {lim}
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Section 8: Sources (Render ONLY if supplied) */}
        {sourcesList.length > 0 && (
          <section style={{ marginBottom: '2rem' }} data-testid="brief-section-sources">
            <h3 style={{ fontSize: '1.125rem', borderBottom: '1px solid var(--gov-slate-300)', paddingBottom: '0.35rem', marginBottom: '0.75rem', color: 'var(--gov-navy-950)' }}>
              8. Source References
            </h3>
            <ul style={{ margin: 0, paddingLeft: '1.25rem', fontSize: '0.875rem', lineHeight: 1.5, color: 'var(--gov-slate-700)' }}>
              {sourcesList.map((src, idx) => (
                <li key={src.id || `src-${idx}`} style={{ marginBottom: '0.35rem' }}>
                  <strong>{src.title || src.documentId}</strong>
                  {src.ministry && <span> ({src.ministry})</span>}
                  {src.pageNumber != null && <span> • Page {src.pageNumber}</span>}
                  {src.section && <span> • {src.section}</span>}
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* Document Footer Signoff */}
        <footer
          style={{
            borderTop: '1px solid var(--gov-slate-300)',
            paddingTop: '1rem',
            display: 'flex',
            justifyContent: 'space-between',
            fontSize: '0.75rem',
            color: 'var(--gov-slate-500)',
            marginTop: '2rem',
          }}
        >
          <div>Policy Intelligence Verification ID: {brief.id}</div>
          <div>Official Parliamentary Brief • Zero-Fabrication Standard</div>
        </footer>
      </article>
    </div>
  );
};
